# Generated by Django 4.1.6 on 2023-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="google_id",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="google id"
            ),
        ),
    ]
