# Generated by Django 4.1.6 on 2023-04-03 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nutrition",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="nutrition",
            name="date_added",
        ),
        migrations.AddField(
            model_name="nutrition",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
