apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitnesstracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitnesstracker
  template:
    metadata:
      labels:
        app: fitnesstracker
    spec:
      containers:
        - name: fitnesstracker
          image: cyrilbaah/fitnesstracker
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              value: "django-insecure-!^*^y-ia*tk+i^b)_2@%eodh-htssvks*whwhlkq@3#l*3&_!g"
            - name: DEBUG
              value: "True"
            - name: DB_TYPE
              value: "postgres"
            - name: USE_S3_BUCKET
              value: "False"
            - name: DB_NAME
              value: "fitness"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "amalitech"
            - name: DB_HOST
              value: "aegis-live.ck0dwzfc16xf.eu-west-1.rds.amazonaws.com"
            - name: "DB_PORT"
              value: "5432"











            
