apiVersion: v1
kind: Secret
metadata:
  name: fitnesstracker
type: Opaque
data:
  secret-key: ZGphbmdvLWluc2VjdXJlLWlnIXN6OXMlJG80Z24mQHJwb0BxcCNybiQtIT09YmI5aGMjaXB0bF5pIylhajI0dHJx
  db-password: ZXhhbXBsZTEyMwo=
  db-host: eW91ci1yZHMuZGF0YWJhc2UucmVnaW9uLXh4LXh4LnJkcy5hbWF6b25hd3MuY29tCg==