name: Pull Request Checker

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ dev, staging, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      TEST_DATABASE_PREFIX: test_

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Run Flake8
      run: |
        flake8

    - name: Run Black
      run: |
        black --check .

    - name: Run isort
      run: |
        isort --check-only .

    # - name: Generate coverage report
    #   run: |
    #     coverage run --source='.' manage.py test
    #     coverage report -m

    # - name: Upload coverage report to Codecov
    #   uses: codecov/codecov-action@v2.1.0
    #   with:
    #     flags: unittests
    #     fail_ci_if_error: true
    #     name: codecov-report
    #     files: coverage.xml
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
